defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - perf
  - ema
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_spearman_{val/spearman:.4f}"
  monitor: "val/spearman"  # Monitor Spearman correlation for regression
  mode: "max"
  save_last: True
  save_top_k: 8
  auto_insert_metric_name: False
  every_n_epochs: 1

early_stopping:
  monitor: "val/spearman"
  patience: 2
  min_delta: 0.003
  mode: "max"

model_summary:
  max_depth: 1

rich_progress_bar:
  leave: True
  theme:
    description: "white"
    progress_bar: "#6206E0"
    progress_bar_finished: "#6206E0"
    progress_bar_pulse: "#6206E0"
    batch_progress: "white"
    time: "grey54"
    processing_speed: "grey70"
    metrics: "white"
    metrics_text_delimiter: " â€¢ "
    metrics_format: ".3e"

